version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: gibabank-db
    restart: always
    command: ["postgres", "-c", "lc_messages=en_US.utf8"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: gibabank
    ports:
      - "5433:5432"